# https://docs.litellm.ai/docs/proxy/deploy

FROM python:latest

USER root
WORKDIR /app

ENV HOME=/home/litellm
ENV PATH="${HOME}/venv/bin:$PATH"


RUN python -m venv ${HOME}/venv
RUN ${HOME}/venv/bin/pip install --no-cache-dir --upgrade pip

COPY requirements.txt .
RUN --mount=type=cache,target=${HOME}/.cache/pip \
    ${HOME}/venv/bin/pip install -r requirements.txt

COPY config.yaml .

EXPOSE 80/tcp

ENTRYPOINT ["litellm"]
CMD ["--port", "80", "--config", "config.yaml"]